CREATE DATABASE MY_COMPANY ENCODING='UTF-8' LC_COLLATE = 'tr_TR.UTF-8' LC_CTYPE='tr_TR.UTF-8' TEMPLATE template0;

CREATE SCHEMA AUTHENTICATION;
CREATE SCHEMA SYSTEM;

CREATE TABLE IF NOT EXISTS AUTHENTICATION.USER (
   USERNAME VARCHAR(100) PRIMARY KEY,
   PASSWORD TEXT NOT NULL,
   PASSWORD2 TEXT,
   PASSWORD3 TEXT,
   PASSWORD_VALID_UNTIL TIMESTAMP,
   PROVIDER VARCHAR(20) NOT NULL,
   PROVIDER_ID VARCHAR(100),
   STATUS VARCHAR(10) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUTHENTICATION.USER_TOKEN (
   ID INT PRIMARY KEY,
   USERNAME VARCHAR(100) NOT NULL,
   TYPE VARCHAR(50) NOT NULL,
   STATUS VARCHAR(10) NOT NULL,
   TOKEN VARCHAR(255) UNIQUE NOT NULL,
   EXPIRES_AT TIMESTAMP,
   USED_AT TIMESTAMP,
   IP_ADDRESS VARCHAR(20),
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUTHENTICATION.ROLE (
   CODE VARCHAR(100) PRIMARY KEY,
   NAME VARCHAR(200) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUTHENTICATION.MENU (
   CODE VARCHAR(100) PRIMARY KEY,
   NAME VARCHAR(200) NOT NULL,
   PATH VARCHAR(500) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUTHENTICATION.USER_ROLE (
   USERNAME VARCHAR(100) NOT NULL,
   ROLE_CODE VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (USERNAME, ROLE_CODE),
   CONSTRAINT USER_ROLE_USER_FK FOREIGN KEY (USERNAME)
          REFERENCES AUTHENTICATION.USER(USERNAME)
          ON DELETE CASCADE
          ON UPDATE CASCADE,
   CONSTRAINT USER_ROLE_ROLE_FK FOREIGN KEY (ROLE_CODE)
          REFERENCES AUTHENTICATION.ROLE(CODE)
          ON DELETE CASCADE
          ON UPDATE CASCADE
);

CREATE TABLE AUTHENTICATION.ROLE_MENU (
   ROLE_CODE VARCHAR(100) NOT NULL,
   MENU_CODE VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ROLE_CODE, MENU_CODE),
   CONSTRAINT ROLE_MENU_ROLE_FK FOREIGN KEY (ROLE_CODE)
          REFERENCES AUTHENTICATION.ROLE(CODE)
          ON DELETE CASCADE
          ON UPDATE CASCADE,
   CONSTRAINT ROLE_MENU_MENU_FK FOREIGN KEY (MENU_CODE)
          REFERENCES AUTHENTICATION.MENU(CODE)
          ON DELETE CASCADE
          ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SYSTEM.PARAMETER (
   CODE VARCHAR(100) PRIMARY KEY,
   TYPE VARCHAR(100) NOT NULL,
   VALUE TEXT NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--ADMIN-123
INSERT INTO AUTHENTICATION.USER ( USERNAME, PASSWORD, PASSWORD2, PASSWORD3, PASSWORD_VALID_UNTIL, PROVIDER, PROVIDER_ID, STATUS, CREATED_AT )
VALUES ('ADMIN', '$2a$10$hG3WpmVQ.4fY7NWiyp484un75Kxt3jmA8.f2piu.3.fCCRf3f1kyu', NULL, NULL, (CURRENT_TIMESTAMP + INTERVAL '90 days'), 'LOCAL', NULL, 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO AUTHENTICATION.ROLE ( CODE, NAME, CREATED_AT )
VALUES ('SYSTEM_ADMINISTRATOR', 'SYSTEM_ADMINISTRATOR', CURRENT_TIMESTAMP);

INSERT INTO AUTHENTICATION.USER_ROLE ( USERNAME, ROLE_CODE, CREATED_AT )
VALUES ('ADMIN', 'SYSTEM_ADMINISTRATOR', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_CHARACTER_LONG_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_CHARACTER_LONG', 'NUMERIC', '8', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_UPPERCASE_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_LOWERCASE_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_DIGIT_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('LAST_3_PREVIOUS_PASSWORD_DIFFERENT_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_VALIDATION_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_EXPIRATION_DAYS', 'NUMERIC', '90', CURRENT_TIMESTAMP);
