CREATE DATABASE MY_COMPANY ENCODING='UTF-8' LC_COLLATE = 'tr_TR.UTF-8' LC_CTYPE='tr_TR.UTF-8' TEMPLATE template0;

CREATE SCHEMA AUTHENTICATION;
CREATE SCHEMA SYSTEM;

CREATE TABLE IF NOT EXISTS AUTHENTICATION.USER (
   USERNAME VARCHAR(100) PRIMARY KEY,
   PASSWORD TEXT NOT NULL,
   PASSWORD2 TEXT,
   PASSWORD3 TEXT,
   PROVIDER VARCHAR(20) NOT NULL,
   PROVIDER_ID VARCHAR(100),
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUTHENTICATION.ROLE (
   CODE VARCHAR(100) PRIMARY KEY,
   NAME VARCHAR(200) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS AUTHENTICATION.MENU (
   CODE VARCHAR(100) PRIMARY KEY,
   NAME VARCHAR(200) NOT NULL,
   PATH VARCHAR(500) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUTHENTICATION.USER_ROLE (
   USERNAME VARCHAR(100) NOT NULL,
   ROLE_CODE VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (USERNAME, ROLE_CODE),
   CONSTRAINT USER_ROLE_USER_FK FOREIGN KEY (USERNAME)
          REFERENCES AUTHENTICATION.USER(USERNAME)
          ON DELETE CASCADE
          ON UPDATE CASCADE,
   CONSTRAINT USER_ROLE_ROLE_FK FOREIGN KEY (ROLE_CODE)
          REFERENCES AUTHENTICATION.ROLE(CODE)
          ON DELETE CASCADE
          ON UPDATE CASCADE
);

CREATE TABLE AUTHENTICATION.ROLE_MENU (
   ROLE_CODE VARCHAR(100) NOT NULL,
   MENU_CODE VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ROLE_CODE, MENU_CODE),
   CONSTRAINT ROLE_MENU_ROLE_FK FOREIGN KEY (ROLE_CODE)
          REFERENCES AUTHENTICATION.ROLE(CODE)
          ON DELETE CASCADE
          ON UPDATE CASCADE,
   CONSTRAINT ROLE_MENU_MENU_FK FOREIGN KEY (MENU_CODE)
          REFERENCES AUTHENTICATION.MENU(CODE)
          ON DELETE CASCADE
          ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SYSTEM.PARAMETER (
   CODE VARCHAR(100) PRIMARY KEY,
   TYPE VARCHAR(100) NOT NULL,
   VALUE TEXT NOT NULL,
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--admin-admin
INSERT INTO AUTHENTICATION.USER ( USERNAME, PASSWORD, PASSWORD2, PASSWORD3, PROVIDER, PROVIDER_ID, CREATED_AT )
VALUES ('admin', '$2a$10$GpjqI0xExRcLcBAlaSgm8uC4mwaq0ysrpdOiM0Ull0PpmEP00FaVS', NULL, NULL, 'LOCAL', NULL, CURRENT_TIMESTAMP);

INSERT INTO AUTHENTICATION.ROLE ( CODE, NAME, CREATED_AT )
VALUES ('admin', 'Admin', CURRENT_TIMESTAMP);

INSERT INTO AUTHENTICATION.USER_ROLE ( USERNAME, ROLE_CODE, CREATED_AT )
VALUES ('admin', 'admin', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_CHARACTER_LONG_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_CHARACTER_LONG', 'NUMERIC', '8', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_UPPERCASE_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_LOWERCASE_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_DIGIT_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO SYSTEM.PARAMETER ( CODE, TYPE, VALUE, CREATED_AT )
VALUES ('PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER_CONTROL', 'STATUS', 'ACTIVE', CURRENT_TIMESTAMP);
