export const STATUSES = {
    ACTIVE: "ACTIVE",
    PASSIVE: "PASSIVE",
} as const;
export type STATUS = typeof STATUSES[keyof typeof STATUSES];

//export const LANGUAGES = ["tr", "en", "de", "ru", "ar"] as const;
export const LANGUAGES = { TR: "tr", EN: "en" } as const;
export type LANGUAGE = typeof LANGUAGES[keyof typeof LANGUAGES];

export const PROVIDERS = {
    LOCAL: "LOCAL",
    GOOGLE: "GOOGLE"
} as const;
export type PROVIDER = typeof PROVIDERS[keyof typeof PROVIDERS];


export const ERROR_CODES = {
    REQUIRED_FIELD: "REQUIRED_FIELD",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    RESET_PASSWORD_TOKEN_EXPIRED: "RESET_PASSWORD_TOKEN_EXPIRED",
    RESET_PASSWORD_TOKEN_NOT_FOUND: "RESET_PASSWORD_TOKEN_NOT_FOUND",
    TOKEN_VALIDATION_ERROR: "TOKEN_VALIDATION_ERROR",
    PASSIVE_USER: "PASSIVE_USER",
    INCORRECT_USERNAME_OR_PASSWORD: "INCORRECT_USERNAME_OR_PASSWORD",
    INCORRECT_OLD_PASSWORD: "INCORRECT_OLD_PASSWORD",
    PASSWORD_DOES_NOT_CONFIRM: "PASSWORD_DOES_NOT_CONFIRM",
    PASSWORD_AT_LEAST_CHARACTERS_LONG: "PASSWORD_AT_LEAST_CHARACTERS_LONG",
    PASSWORD_AT_LEAST_ONE_UPPERCASE: "PASSWORD_AT_LEAST_ONE_UPPERCASE",
    PASSWORD_AT_LEAST_ONE_LOWERCASE: "PASSWORD_AT_LEAST_ONE_LOWERCASE",
    PASSWORD_AT_LEAST_ONE_DIGIT: "PASSWORD_AT_LEAST_ONE_DIGIT",
    PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER: "PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER",
    LAST_3_PREVIOUS_PASSWORD_DIFFERENT: "LAST_3_PREVIOUS_PASSWORD_DIFFERENT",
    DO_NOT_HAVE_PERMISSION: "DO_NOT_HAVE_PERMISSION",
    USERNAME_ALREADY_REGISTERED: "USERNAME_ALREADY_REGISTERED",
    USED_BY_THE_SYSTEM: "USED_BY_THE_SYSTEM",
    RECORD_WITH_ID_NOT_FOUND: "RECORD_WITH_ID_NOT_FOUND"
} as const;
export type ERROR_CODE = typeof ERROR_CODES[keyof typeof ERROR_CODES];
