export const ERROR_CODE = {
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INCORRECT_USERNAME_OR_PASSWORD: "INCORRECT_USERNAME_OR_PASSWORD",
    INCORRECT_OLD_PASSWORD: "INCORRECT_OLD_PASSWORD",
    NEW_PASSWORD_DOES_NOT_CONFIRM: "NEW_PASSWORD_DOES_NOT_CONFIRM"
}
