package com.my_company.constants.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    VALIDATION,
    GENERAL,
    TOKEN_EXPIRED,
    TOKEN_VALIDATION_ERROR,
    INCORRECT_USERNAME_OR_PASSWORD,
    DO_NOT_HAVE_PERMISSION,
    REQUIRED_FIELD,
    INCORRECT_OLD_PASSWORD,
    NEW_PASSWORD_DOES_NOT_CONFIRM,
    USERNAME_ALREADY_REGISTERED,
    USED_BY_THE_SYSTEM,
    RECORD_WITH_ID_NOT_FOUND,
    PASSWORD_AT_LEAST_CHARACTERS_LONG,
    PASSWORD_AT_LEAST_ONE_UPPERCASE,
    PASSWORD_AT_LEAST_ONE_LOWERCASE,
    PASSWORD_AT_LEAST_ONE_DIGIT,
    PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER,
    LAST_3_PREVIOUS_PASSWORD_DIFFERENT
}