package com.my_company.constants.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ParameterCode {
    PASSWORD_AT_LEAST_CHARACTER_LONG_CONTROL,
    PASSWORD_AT_LEAST_CHARACTER_LONG,
    PASSWORD_AT_LEAST_ONE_UPPERCASE_CONTROL,
    PASSWORD_AT_LEAST_ONE_LOWERCASE_CONTROL,
    PASSWORD_AT_LEAST_ONE_DIGIT_CONTROL,
    PASSWORD_AT_LEAST_ONE_SPECIAL_CHARACTER_CONTROL,
    LAST_3_PREVIOUS_PASSWORD_DIFFERENT_CONTROL,
    PASSWORD_VALIDATION_CONTROL,
    PASSWORD_EXPIRATION_CONTROL,
    PASSWORD_EXPIRATION_DAYS,
    RESET_PASSWORD_TOKEN_EXPIRATION_CONTROL,
    RESET_PASSWORD_TOKEN_EXPIRATION_MINUTES,
    VERIFY_ACCOUNT_TOKEN_EXPIRATION_CONTROL,
    VERIFY_ACCOUNT_TOKEN_EXPIRATION_MINUTES,
}
