server:
  servlet:
    context-path: /my-company
  port: 8090

spring:
  application:
    name: my-company
  datasource:
    driver-class-name: org.postgresql.Driver
    ####################################################################################################
    # setx MY_COMPANY_DB_URL "URL_VALUE" -> For Windows
    # setx MY_COMPANY_DB_USERNAME "USERNAME_VALUE" -> For Windows
    # setx MY_COMPANY_DB_PASSWORD "PASSWORD_VALUE" -> For Windows
    # export MY_COMPANY_DB_URL=URL_VALUE -> For Linux / macOS (bash):
    # export MY_COMPANY_DB_USERNAME=USERNAME_VALUE -> For Linux / macOS (bash):
    # export MY_COMPANY_DB_PASSWORD=PASSWORD_VALUE -> For Linux / macOS (bash):
    ####################################################################################################
    # Intellij de; Run → Edit Configurations → Environment Variables → Edit Environment Variables → Add
    # MY_COMPANY_DB_URL → URL_VALUE
    # MY_COMPANY_DB_USERNAME → USERNAME_VALUE
    # MY_COMPANY_DB_PASSWORD → PASSWORD_VALUE
    ####################################################################################################
    url: jdbc:postgresql://${MY_COMPANY_DB_URL}
    username: ${MY_COMPANY_DB_USERNAME}
    password: ${MY_COMPANY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #http://localhost:8025
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

springdoc:
  swagger-ui.path: /swagger-ui.html

app:
  frontend:
    url: http://localhost:8080

